#include "fuzz.h"
int init_data_size=0;//这一句在程序结束后会进行修改
uint8_t copydata[init_data_size];
SSL* _n_do_ssl_write_s_copy;
unsigned char* _n_do_ssl_write_buf_copy;
unsigned int _n_do_ssl_write_len_copy;
unsigned int _n_do_ssl_write_p_copy;
int _n_do_ssl_write_mac_size_copy;
unsigned char* _n_do_ssl_write_pp_copy;
unsigned int _n_do_ssl_write_olen_copy;
int n_do_ssl_write_return_copy;
int write_pending_return_copy;
int loop=0;
int real_loop=0;


extern "C" int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
 {
	SSL* _n_do_ssl_write_s_;
	unsigned char* _n_do_ssl_write_buf_;
	unsigned int _n_do_ssl_write_len_;
	unsigned int _n_do_ssl_write_p_;
	int _n_do_ssl_write_mac_size_;
	unsigned char* _n_do_ssl_write_pp_;
	unsigned int _n_do_ssl_write_olen_;
	int n_do_ssl_write_return_;
	int write_pending_return_;
	if (loop/1000==0)
	{
		if (size>init_data_size)
		{


		}
		_n_do_ssl_write_s_copy=(SSL*)&data[0];
		_n_do_ssl_write_s_copy->method=(SSL_METHOD*)&data[808]; //指针可以变，但是指针指向的内容不能变
		_n_do_ssl_write_s_copy->method->ssl3_enc=(struct ssl3_enc_method*)&data[1848]; //这里就是指针指向的内容
		_n_do_ssl_write_s_copy->method->ssl3_enc->client_finished_label=(char*)&data[3000];//这里的指针指向的内容保存到了其他地方，所以不是const指针指向的内容
		_n_do_ssl_write_s_copy->method->ssl3_enc->server_finished_label=(char*)&data[3100];//所以这里赋值是没有错的
		//所以我这里只需要将第二句的内容用相应的机制做修改就行了
		//需要计算ssl3_enc在data中占第几字节
		//把copydata中将相应的两字节数据的内容修改为data中某个字节的首地址
		//long是占两个字节的
		//uint8_t *a=&data[x];
		//long *b=(long *)a;
		//*b=&data[y];
		//在进行data地址连接的时候需要继续成员变量所在data中的字节下标x，以及应该指向的字节下标y


		_n_do_ssl_write_s_copy->rbio=(BIO*)&data[3200];
		_n_do_ssl_write_s_copy->rbio->method=(BIO_METHOD*)&data[4464];
		_n_do_ssl_write_s_copy->rbio->method->name=(char*)&data[5808];
		_n_do_ssl_write_s_copy->rbio->cb_arg=(char*)&data[5908];
		_n_do_ssl_write_s_copy->rbio->ptr=(void*)&data[6008];
		_n_do_ssl_write_s_copy->wbio=(BIO*)&data[6108];
		_n_do_ssl_write_s_copy->bbio=(BIO*)&data[6108];
		_n_do_ssl_write_s_copy->init_buf=(BUF_MEM*)&data[6108];
		_n_do_ssl_write_s_copy->init_buf->data=(char*)&data[7556];
		_n_do_ssl_write_s_copy->init_msg=(void*)&data[7656];
		_n_do_ssl_write_s_copy->packet=(unsigned char*)&data[7756];
		_n_do_ssl_write_s_copy->s2=(struct ssl2_state_st*)&data[7856];
		_n_do_ssl_write_s_copy->s2->wpend_buf=(unsigned char*)&data[9648];
		_n_do_ssl_write_s_copy->s2->rbuf=(unsigned char*)&data[9748];
		_n_do_ssl_write_s_copy->s2->wbuf=(unsigned char*)&data[9848];
		_n_do_ssl_write_s_copy->s2->write_ptr=(unsigned char*)&data[9948];
		_n_do_ssl_write_s_copy->s2->ract_data=(unsigned char*)&data[10048];
		_n_do_ssl_write_s_copy->s2->wact_data=(unsigned char*)&data[10148];
		_n_do_ssl_write_s_copy->s2->mac_data=(unsigned char*)&data[10248];
		_n_do_ssl_write_s_copy->s2->read_key=(unsigned char*)&data[10348];
		_n_do_ssl_write_s_copy->s2->write_key=(unsigned char*)&data[10448];
		_n_do_ssl_write_s_copy->s3=(struct ssl3_state_st*)&data[12412];
		_n_do_ssl_write_s_copy->s3->rbuf.buf=(unsigned char*)&data[18564];
		_n_do_ssl_write_s_copy->s3->rrec.data=(unsigned char*)&data[21808];
		_n_do_ssl_write_s_copy->s3->rrec.input=(unsigned char*)&data[21908];
		_n_do_ssl_write_s_copy->s3->rrec.comp=(unsigned char*)&data[22008];
		_n_do_ssl_write_s_copy->s3->wpend_buf=(unsigned char*)&data[22108];
		_n_do_ssl_write_s_copy->s3->handshake_buffer=(BIO*)&data[22208];
		_n_do_ssl_write_s_copy->s3->handshake_dgst=(EVP_MD_CTX**)&data[22208];
		*(_n_do_ssl_write_s_copy->s3->handshake_dgst)=(EVP_MD_CTX*)&data[22216];
		EVP_MD_CTX* evd=*(_n_do_ssl_write_s_copy->s3->handshake_dgst);
		evd->digest=(EVP_MD*)&data[25400];
		evd->engine=(ENGINE*)&data[28712];
		evd->md_data=(void*)&data[32024];
		evd->pctx=(EVP_PKEY_CTX*)&data[32124];
		_n_do_ssl_write_s_copy->s3->client_opaque_prf_input=(void*)&data[35436];
		_n_do_ssl_write_s_copy->s3->server_opaque_prf_input=(void*)&data[35536];
		_n_do_ssl_write_s_copy->d1=(struct dtls1_state_st*)&data[35636];
		_n_do_ssl_write_s_copy->d1->unprocessed_rcds.q=(pqueue)&data[48284];
		_n_do_ssl_write_s_copy->d1->buffered_messages=(pqueue)&data[52516];
		_n_do_ssl_write_s_copy->d1->sent_messages=(pqueue)&data[52516];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.enc_write_ctx=(EVP_CIPHER_CTX*)&data[61196];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.enc_write_ctx->cipher=(EVP_CIPHER*)&data[65724];
		// _n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.enc_write_ctx->cipher->app_data=(void*)&data[70340];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.enc_write_ctx->engine=(ENGINE*)&data[70440];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.enc_write_ctx->app_data=(void*)&data[70440];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.enc_write_ctx->cipher_data=(void*)&data[70540];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.write_hash=(EVP_MD_CTX*)&data[70640];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.compress=(COMP_CTX*)&data[70640];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.compress->meth=(COMP_METHOD*)&data[75312];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.compress->meth->name=(char*)&data[80048];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.compress->ex_data.sk=(struct stack_st_void*)&data[81508];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.compress->ex_data.sk->stack.data=(char**)&data[84424];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session=(SSL_SESSION*)&data[84524];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->psk_identity_hint=(char*)&data[89612];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->psk_identity=(char*)&data[89712];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert=(struct sess_cert_st*)&data[89812];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->cert_chain=(struct stack_st_X509*)&data[95148];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key=(CERT_PKEY*)&data[100516];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509=(X509*)&data[105908];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info=(X509_CINF*)&data[111484];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->version=(ASN1_INTEGER*)&data[117164];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->version->data=(unsigned char*)&data[122868];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->serialNumber=(ASN1_INTEGER*)&data[122968];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->signature=(X509_ALGOR*)&data[122968];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->signature->algorithm=(ASN1_OBJECT*)&data[128688];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->signature->algorithm->sn=(char*)&data[134448];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->signature->algorithm->ln=(char*)&data[134548];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->signature->algorithm->data=(unsigned char*)&data[134648];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->signature->parameter=(ASN1_TYPE*)&data[134748];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->issuer=(X509_NAME*)&data[140524];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->issuer->entries=(struct stack_st_X509_NAME_ENTRY*)&data[146340];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->issuer->bytes=(BUF_MEM*)&data[152188];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->issuer->canon_enc=(unsigned char*)&data[152188];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->validity=(X509_VAL*)&data[152288];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->validity->notBefore=(ASN1_TIME*)&data[158152];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->validity->notAfter=(ASN1_TIME*)&data[158152];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->subject=(X509_NAME*)&data[158152];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->key=(X509_PUBKEY*)&data[158152];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->key->algor=(X509_ALGOR*)&data[164040];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->key->public_key=(ASN1_BIT_STRING*)&data[164040];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->key->pkey=(EVP_PKEY*)&data[164040];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->key->pkey->ameth=(EVP_PKEY_ASN1_METHOD*)&data[169984];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->key->pkey->engine=(ENGINE*)&data[175928];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->key->pkey->attributes=(struct stack_st_X509_ATTRIBUTE*)&data[175928];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->issuerUID=(ASN1_BIT_STRING*)&data[181904];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->subjectUID=(ASN1_BIT_STRING*)&data[181904];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->extensions=(struct stack_st_X509_EXTENSION*)&data[181904];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->enc.enc=(unsigned char*)&data[193944];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->sig_alg=(X509_ALGOR*)&data[194044];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->signature=(ASN1_BIT_STRING*)&data[194044];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->name=(char*)&data[194044];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->skid=(ASN1_OCTET_STRING*)&data[194144];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->akid=(AUTHORITY_KEYID*)&data[194144];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->policy_cache=(X509_POLICY_CACHE*)&data[200176];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->crldp=(struct stack_st_DIST_POINT*)&data[206208];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->altname=(struct stack_st_GENERAL_NAME*)&data[212240];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->nc=(NAME_CONSTRAINTS*)&data[218272];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->aux=(X509_CERT_AUX*)&data[224304];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->aux->trust=(struct stack_st_ASN1_OBJECT*)&data[230376];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->aux->reject=(struct stack_st_ASN1_OBJECT*)&data[236480];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->aux->alias=(ASN1_UTF8STRING*)&data[236480];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->aux->keyid=(ASN1_OCTET_STRING*)&data[236480];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->aux->other=(struct stack_st_X509_ALGOR*)&data[236480];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->privatekey=(EVP_PKEY*)&data[242616];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->digest=(EVP_MD*)&data[242616];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp=(RSA*)&data[242616];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->meth=(RSA_METHOD*)&data[248920];
		// _n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->meth->name=(char*)&data[255336];
		// _n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->meth->app_data=(char*)&data[255436];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->engine=(ENGINE*)&data[255536];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->n=(BIGNUM*)&data[255536];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->n->d=(unsigned int*)&data[261976];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->e=(BIGNUM*)&data[261976];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->d=(BIGNUM*)&data[261976];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->p=(BIGNUM*)&data[261976];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->q=(BIGNUM*)&data[261976];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->dmp1=(BIGNUM*)&data[261976];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->dmq1=(BIGNUM*)&data[261976];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->iqmp=(BIGNUM*)&data[261976];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->_method_mod_n=(BN_MONT_CTX*)&data[261976];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->_method_mod_p=(BN_MONT_CTX*)&data[268512];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->_method_mod_q=(BN_MONT_CTX*)&data[268512];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->bignum_data=(char*)&data[268512];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->blinding=(BN_BLINDING*)&data[268612];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->mt_blinding=(BN_BLINDING*)&data[275148];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp=(DH*)&data[275148];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->p=(BIGNUM*)&data[281828];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->g=(BIGNUM*)&data[281828];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->pub_key=(BIGNUM*)&data[281828];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->priv_key=(BIGNUM*)&data[281828];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->method_mont_p=(BN_MONT_CTX*)&data[281828];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->q=(BIGNUM*)&data[281828];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->j=(BIGNUM*)&data[281828];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->seed=(unsigned char*)&data[281828];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->counter=(BIGNUM*)&data[281928];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->meth=(DH_METHOD*)&data[281928];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->meth->name=(char*)&data[288680];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->meth->app_data=(char*)&data[288780];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->engine=(ENGINE*)&data[288880];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_ecdh_tmp=(EC_KEY*)&data[288880];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->peer=(X509*)&data[295632];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->cipher=(SSL_CIPHER*)&data[295632];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->cipher->name=(char*)&data[302472];
		_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->ciphers=(struct stack_st_SSL_CIPHER*)&data[302572];
		_n_do_ssl_write_s_copy->msg_callback_arg=(void*)&data[323228];
		_n_do_ssl_write_s_copy->param=(X509_VERIFY_PARAM*)&data[323328];
		_n_do_ssl_write_s_copy->param->name=(char*)&data[330284];
		_n_do_ssl_write_s_copy->param->policies=(struct stack_st_ASN1_OBJECT*)&data[330384];
		_n_do_ssl_write_s_copy->cipher_list=(struct stack_st_SSL_CIPHER*)&data[330384];
		_n_do_ssl_write_s_copy->cipher_list_by_id=(struct stack_st_SSL_CIPHER*)&data[330384];
		_n_do_ssl_write_s_copy->enc_read_ctx=(EVP_CIPHER_CTX*)&data[330384];
		_n_do_ssl_write_s_copy->read_hash=(EVP_MD_CTX*)&data[330384];
		_n_do_ssl_write_s_copy->expand=(COMP_CTX*)&data[330384];
		_n_do_ssl_write_s_copy->enc_write_ctx=(EVP_CIPHER_CTX*)&data[330384];
		_n_do_ssl_write_s_copy->write_hash=(EVP_MD_CTX*)&data[330384];
		_n_do_ssl_write_s_copy->compress=(COMP_CTX*)&data[330384];
		_n_do_ssl_write_s_copy->cert=(struct cert_st*)&data[330384];
		_n_do_ssl_write_s_copy->cert->key=(CERT_PKEY*)&data[337636];
		_n_do_ssl_write_s_copy->cert->rsa_tmp=(RSA*)&data[337636];
		_n_do_ssl_write_s_copy->cert->dh_tmp=(DH*)&data[337636];
		_n_do_ssl_write_s_copy->cert->ecdh_tmp=(EC_KEY*)&data[337636];
		_n_do_ssl_write_s_copy->session=(SSL_SESSION*)&data[337636];
		_n_do_ssl_write_s_copy->ctx=(SSL_CTX*)&data[337636];
		_n_do_ssl_write_s_copy->ctx->method=(SSL_METHOD*)&data[345624];
		_n_do_ssl_write_s_copy->ctx->cipher_list=(struct stack_st_SSL_CIPHER*)&data[345624];
		_n_do_ssl_write_s_copy->ctx->cipher_list_by_id=(struct stack_st_SSL_CIPHER*)&data[345624];
		_n_do_ssl_write_s_copy->ctx->cert_store=(struct x509_store_st*)&data[345624];
		_n_do_ssl_write_s_copy->ctx->cert_store->objs=(struct stack_st_X509_OBJECT*)&data[353756];
		_n_do_ssl_write_s_copy->ctx->cert_store->get_cert_methods=(struct stack_st_X509_LOOKUP*)&data[361920];
		_n_do_ssl_write_s_copy->ctx->cert_store->param=(X509_VERIFY_PARAM*)&data[370116];
		_n_do_ssl_write_s_copy->ctx->sessions=(struct lhash_st_SSL_SESSION*)&data[370116];
		_n_do_ssl_write_s_copy->ctx->session_cache_head=(struct ssl_session_st*)&data[378316];
		_n_do_ssl_write_s_copy->ctx->session_cache_tail=(struct ssl_session_st*)&data[378316];
		_n_do_ssl_write_s_copy->ctx->app_verify_arg=(void*)&data[378316];
		_n_do_ssl_write_s_copy->ctx->default_passwd_callback_userdata=(void*)&data[378416];
		_n_do_ssl_write_s_copy->ctx->rsa_md5=(EVP_MD*)&data[378516];
		_n_do_ssl_write_s_copy->ctx->md5=(EVP_MD*)&data[378516];
		_n_do_ssl_write_s_copy->ctx->sha1=(EVP_MD*)&data[378516];
		_n_do_ssl_write_s_copy->ctx->extra_certs=(struct stack_st_X509*)&data[378516];
		_n_do_ssl_write_s_copy->ctx->comp_methods=(struct stack_st_SSL_COMP*)&data[378516];
		_n_do_ssl_write_s_copy->ctx->client_CA=(struct stack_st_X509_NAME*)&data[386748];
		_n_do_ssl_write_s_copy->ctx->cert=(struct cert_st*)&data[395012];
		_n_do_ssl_write_s_copy->ctx->msg_callback_arg=(void*)&data[395012];
		_n_do_ssl_write_s_copy->ctx->param=(X509_VERIFY_PARAM*)&data[395112];
		_n_do_ssl_write_s_copy->ctx->client_cert_engine=(ENGINE*)&data[395112];
		_n_do_ssl_write_s_copy->ctx->tlsext_servername_arg=(void*)&data[395112];
		_n_do_ssl_write_s_copy->ctx->tlsext_status_arg=(void*)&data[395212];
		_n_do_ssl_write_s_copy->ctx->tlsext_opaque_prf_input_callback_arg=(void*)&data[395312];
		_n_do_ssl_write_s_copy->ctx->psk_identity_hint=(char*)&data[395412];
		_n_do_ssl_write_s_copy->ctx->wbuf_freelist=(struct ssl3_buf_freelist_st*)&data[395512];
		_n_do_ssl_write_s_copy->ctx->wbuf_freelist->head=(struct ssl3_buf_freelist_entry_st*)&data[403800];
		_n_do_ssl_write_s_copy->ctx->rbuf_freelist=(struct ssl3_buf_freelist_st*)&data[412096];
		_n_do_ssl_write_s_copy->ctx->srp_ctx.SRP_cb_arg=(void*)&data[420520];
		_n_do_ssl_write_s_copy->ctx->srp_ctx.login=(char*)&data[420620];
		_n_do_ssl_write_s_copy->ctx->srp_ctx.N=(BIGNUM*)&data[420720];
		_n_do_ssl_write_s_copy->ctx->srp_ctx.g=(BIGNUM*)&data[420720];
		_n_do_ssl_write_s_copy->ctx->srp_ctx.s=(BIGNUM*)&data[420720];
		_n_do_ssl_write_s_copy->ctx->srp_ctx.B=(BIGNUM*)&data[420720];
		_n_do_ssl_write_s_copy->ctx->srp_ctx.A=(BIGNUM*)&data[420720];
		_n_do_ssl_write_s_copy->ctx->srp_ctx.a=(BIGNUM*)&data[420720];
		_n_do_ssl_write_s_copy->ctx->srp_ctx.b=(BIGNUM*)&data[420720];
		_n_do_ssl_write_s_copy->ctx->srp_ctx.v=(BIGNUM*)&data[420720];
		_n_do_ssl_write_s_copy->ctx->srp_ctx.info=(char*)&data[420720];
		_n_do_ssl_write_s_copy->ctx->next_protos_advertised_cb_arg=(void*)&data[420820];
		_n_do_ssl_write_s_copy->ctx->next_proto_select_cb_arg=(void*)&data[420920];
		_n_do_ssl_write_s_copy->ctx->srtp_profiles=(struct stack_st_SRTP_PROTECTION_PROFILE*)&data[421020];
		_n_do_ssl_write_s_copy->client_CA=(struct stack_st_X509_NAME*)&data[429476];
		_n_do_ssl_write_s_copy->tlsext_debug_arg=(void*)&data[429476];
		_n_do_ssl_write_s_copy->tlsext_hostname=(char*)&data[429576];
		_n_do_ssl_write_s_copy->tlsext_ocsp_ids=(struct stack_st_OCSP_RESPID*)&data[429676];
		_n_do_ssl_write_s_copy->tlsext_ocsp_exts=(X509_EXTENSIONS*)&data[438132];
		_n_do_ssl_write_s_copy->tlsext_ocsp_resp=(unsigned char*)&data[438132];
		_n_do_ssl_write_s_copy->tlsext_ecpointformatlist=(unsigned char*)&data[438232];
		_n_do_ssl_write_s_copy->tlsext_ellipticcurvelist=(unsigned char*)&data[438332];
		_n_do_ssl_write_s_copy->tlsext_opaque_prf_input=(void*)&data[438432];
		_n_do_ssl_write_s_copy->tlsext_session_ticket=(TLS_SESSION_TICKET_EXT*)&data[438532];
		_n_do_ssl_write_s_copy->tlsext_session_ticket->data=(void*)&data[447004];
		_n_do_ssl_write_s_copy->tls_session_ticket_ext_cb_arg=(void*)&data[447104];
		_n_do_ssl_write_s_copy->tls_session_secret_cb_arg=(void*)&data[447204];
		_n_do_ssl_write_s_copy->initial_ctx=(SSL_CTX*)&data[447304];
		_n_do_ssl_write_s_copy->next_proto_negotiated=(unsigned char*)&data[447304];
		_n_do_ssl_write_s_copy->srtp_profiles=(struct stack_st_SRTP_PROTECTION_PROFILE*)&data[447404];
		_n_do_ssl_write_s_copy->srtp_profile=(SRTP_PROTECTION_PROFILE*)&data[447404];
		_n_do_ssl_write_s_copy->srtp_profile->name=(char*)&data[455892];
		_n_do_ssl_write_buf_copy=(unsigned char*)&data[455992];
		_n_do_ssl_write_len_copy=(unsigned int)data[456092];
		_n_do_ssl_write_p_copy=(unsigned int)data[456096];
		_n_do_ssl_write_mac_size_copy=(int)data[456100];
		_n_do_ssl_write_pp_copy=(unsigned char*)&data[456104];
		_n_do_ssl_write_olen_copy=(unsigned int)data[456204];
		n_do_ssl_write_return_copy=(int)data[456208];
		write_pending_return_copy=(int)data[456212];
		if (size>=456216)
		{
			s2_pkt610s2_pkt490_1(_n_do_ssl_write_s_,_n_do_ssl_write_buf_,_n_do_ssl_write_len_,_n_do_ssl_write_p_,_n_do_ssl_write_mac_size_,_n_do_ssl_write_pp_,_n_do_ssl_write_olen_,n_do_ssl_write_return_,write_pending_return_);
			for (int i=0;i<(size<456216?size:456216);i++)
			{
				copydata[i]=data[i];
			}
			_n_do_ssl_write_s_copy=(SSL*)&copydata[0];
			_n_do_ssl_write_s_copy->method=(SSL_METHOD*)&copydata[808];
			_n_do_ssl_write_s_copy->method->ssl3_enc=(struct ssl3_enc_method*)&copydata[1848];
			_n_do_ssl_write_s_copy->method->ssl3_enc->client_finished_label=(char*)&copydata[3000];
			_n_do_ssl_write_s_copy->method->ssl3_enc->server_finished_label=(char*)&copydata[3100];
			_n_do_ssl_write_s_copy->rbio=(BIO*)&copydata[3200];
			_n_do_ssl_write_s_copy->rbio->method=(BIO_METHOD*)&copydata[4464];
			_n_do_ssl_write_s_copy->rbio->method->name=(char*)&copydata[5808];
			_n_do_ssl_write_s_copy->rbio->cb_arg=(char*)&copydata[5908];
			_n_do_ssl_write_s_copy->rbio->ptr=(void*)&copydata[6008];
			_n_do_ssl_write_s_copy->wbio=(BIO*)&copydata[6108];
			_n_do_ssl_write_s_copy->bbio=(BIO*)&copydata[6108];
			_n_do_ssl_write_s_copy->init_buf=(BUF_MEM*)&copydata[6108];
			_n_do_ssl_write_s_copy->init_buf->data=(char*)&copydata[7556];
			_n_do_ssl_write_s_copy->init_msg=(void*)&copydata[7656];
			_n_do_ssl_write_s_copy->packet=(unsigned char*)&copydata[7756];
			_n_do_ssl_write_s_copy->s2=(struct ssl2_state_st*)&copydata[7856];
			_n_do_ssl_write_s_copy->s2->wpend_buf=(unsigned char*)&copydata[9648];
			_n_do_ssl_write_s_copy->s2->rbuf=(unsigned char*)&copydata[9748];
			_n_do_ssl_write_s_copy->s2->wbuf=(unsigned char*)&copydata[9848];
			_n_do_ssl_write_s_copy->s2->write_ptr=(unsigned char*)&copydata[9948];
			_n_do_ssl_write_s_copy->s2->ract_data=(unsigned char*)&copydata[10048];
			_n_do_ssl_write_s_copy->s2->wact_data=(unsigned char*)&copydata[10148];
			_n_do_ssl_write_s_copy->s2->mac_data=(unsigned char*)&copydata[10248];
			_n_do_ssl_write_s_copy->s2->read_key=(unsigned char*)&copydata[10348];
			_n_do_ssl_write_s_copy->s2->write_key=(unsigned char*)&copydata[10448];
			_n_do_ssl_write_s_copy->s3=(struct ssl3_state_st*)&copydata[12412];
			_n_do_ssl_write_s_copy->s3->rbuf.buf=(unsigned char*)&copydata[18564];
			_n_do_ssl_write_s_copy->s3->rrec.data=(unsigned char*)&copydata[21808];
			_n_do_ssl_write_s_copy->s3->rrec.input=(unsigned char*)&copydata[21908];
			_n_do_ssl_write_s_copy->s3->rrec.comp=(unsigned char*)&copydata[22008];
			_n_do_ssl_write_s_copy->s3->wpend_buf=(unsigned char*)&copydata[22108];
			_n_do_ssl_write_s_copy->s3->handshake_buffer=(BIO*)&copydata[22208];
			_n_do_ssl_write_s_copy->s3->handshake_dgst=(EVP_MD_CTX*)&copydata[22208];
			_n_do_ssl_write_s_copy->s3->handshake_dgst->digest=(EVP_MD*)&copydata[25400];
			_n_do_ssl_write_s_copy->s3->handshake_dgst->engine=(ENGINE*)&copydata[28712];
			_n_do_ssl_write_s_copy->s3->handshake_dgst->md_data=(void*)&copydata[32024];
			_n_do_ssl_write_s_copy->s3->handshake_dgst->pctx=(EVP_PKEY_CTX*)&copydata[32124];
			_n_do_ssl_write_s_copy->s3->client_opaque_prf_input=(void*)&copydata[35436];
			_n_do_ssl_write_s_copy->s3->server_opaque_prf_input=(void*)&copydata[35536];
			_n_do_ssl_write_s_copy->d1=(struct dtls1_state_st*)&copydata[35636];
			_n_do_ssl_write_s_copy->d1->unprocessed_rcds.q=(pqueue*)&copydata[48284];
			_n_do_ssl_write_s_copy->d1->buffered_messages=(pqueue*)&copydata[52516];
			_n_do_ssl_write_s_copy->d1->sent_messages=(pqueue*)&copydata[52516];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.enc_write_ctx=(EVP_CIPHER_CTX*)&copydata[61196];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.enc_write_ctx->cipher=(EVP_CIPHER*)&copydata[65724];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.enc_write_ctx->cipher->app_data=(void*)&copydata[70340];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.enc_write_ctx->engine=(ENGINE*)&copydata[70440];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.enc_write_ctx->app_data=(void*)&copydata[70440];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.enc_write_ctx->cipher_data=(void*)&copydata[70540];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.write_hash=(EVP_MD_CTX*)&copydata[70640];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.compress=(COMP_CTX*)&copydata[70640];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.compress->meth=(COMP_METHOD*)&copydata[75312];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.compress->meth->name=(char*)&copydata[80048];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.compress->ex_data.sk=(struct stack_st_void*)&copydata[81508];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.compress->ex_data.sk->stack.data=(char*)&copydata[84424];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session=(SSL_SESSION*)&copydata[84524];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->psk_identity_hint=(char*)&copydata[89612];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->psk_identity=(char*)&copydata[89712];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert=(struct sess_cert_st*)&copydata[89812];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->cert_chain=(struct stack_st_X509*)&copydata[95148];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key=(CERT_PKEY*)&copydata[100516];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509=(X509*)&copydata[105908];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info=(X509_CINF*)&copydata[111484];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->version=(ASN1_INTEGER*)&copydata[117164];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->version->data=(unsigned char*)&copydata[122868];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->serialNumber=(ASN1_INTEGER*)&copydata[122968];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->signature=(X509_ALGOR*)&copydata[122968];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->signature->algorithm=(ASN1_OBJECT*)&copydata[128688];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->signature->algorithm->sn=(char*)&copydata[134448];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->signature->algorithm->ln=(char*)&copydata[134548];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->signature->algorithm->data=(unsigned char*)&copydata[134648];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->signature->parameter=(ASN1_TYPE*)&copydata[134748];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->issuer=(X509_NAME*)&copydata[140524];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->issuer->entries=(struct stack_st_X509_NAME_ENTRY*)&copydata[146340];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->issuer->bytes=(BUF_MEM*)&copydata[152188];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->issuer->canon_enc=(unsigned char*)&copydata[152188];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->validity=(X509_VAL*)&copydata[152288];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->validity->notBefore=(ASN1_TIME*)&copydata[158152];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->validity->notAfter=(ASN1_TIME*)&copydata[158152];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->subject=(X509_NAME*)&copydata[158152];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->key=(X509_PUBKEY*)&copydata[158152];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->key->algor=(X509_ALGOR*)&copydata[164040];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->key->public_key=(ASN1_BIT_STRING*)&copydata[164040];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->key->pkey=(EVP_PKEY*)&copydata[164040];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->key->pkey->ameth=(EVP_PKEY_ASN1_METHOD*)&copydata[169984];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->key->pkey->engine=(ENGINE*)&copydata[175928];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->key->pkey->attributes=(struct stack_st_X509_ATTRIBUTE*)&copydata[175928];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->issuerUID=(ASN1_BIT_STRING*)&copydata[181904];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->subjectUID=(ASN1_BIT_STRING*)&copydata[181904];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->extensions=(struct stack_st_X509_EXTENSION*)&copydata[181904];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->cert_info->enc.enc=(unsigned char*)&copydata[193944];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->sig_alg=(X509_ALGOR*)&copydata[194044];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->signature=(ASN1_BIT_STRING*)&copydata[194044];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->name=(char*)&copydata[194044];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->skid=(ASN1_OCTET_STRING*)&copydata[194144];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->akid=(AUTHORITY_KEYID*)&copydata[194144];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->policy_cache=(X509_POLICY_CACHE*)&copydata[200176];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->crldp=(struct stack_st_DIST_POINT*)&copydata[206208];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->altname=(struct stack_st_GENERAL_NAME*)&copydata[212240];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->nc=(NAME_CONSTRAINTS*)&copydata[218272];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->aux=(X509_CERT_AUX*)&copydata[224304];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->aux->trust=(struct stack_st_ASN1_OBJECT*)&copydata[230376];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->aux->reject=(struct stack_st_ASN1_OBJECT*)&copydata[236480];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->aux->alias=(ASN1_UTF8STRING*)&copydata[236480];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->aux->keyid=(ASN1_OCTET_STRING*)&copydata[236480];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->x509->aux->other=(struct stack_st_X509_ALGOR*)&copydata[236480];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->privatekey=(EVP_PKEY*)&copydata[242616];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_key->digest=(EVP_MD*)&copydata[242616];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp=(RSA*)&copydata[242616];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->meth=(RSA_METHOD*)&copydata[248920];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->meth->name=(char*)&copydata[255336];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->meth->app_data=(char*)&copydata[255436];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->engine=(ENGINE*)&copydata[255536];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->n=(BIGNUM*)&copydata[255536];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->n->d=(unsigned int*)&copydata[261976];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->e=(BIGNUM*)&copydata[261976];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->d=(BIGNUM*)&copydata[261976];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->p=(BIGNUM*)&copydata[261976];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->q=(BIGNUM*)&copydata[261976];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->dmp1=(BIGNUM*)&copydata[261976];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->dmq1=(BIGNUM*)&copydata[261976];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->iqmp=(BIGNUM*)&copydata[261976];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->_method_mod_n=(BN_MONT_CTX*)&copydata[261976];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->_method_mod_p=(BN_MONT_CTX*)&copydata[268512];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->_method_mod_q=(BN_MONT_CTX*)&copydata[268512];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->bignum_data=(char*)&copydata[268512];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->blinding=(BN_BLINDING*)&copydata[268612];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_rsa_tmp->mt_blinding=(BN_BLINDING*)&copydata[275148];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp=(DH*)&copydata[275148];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->p=(BIGNUM*)&copydata[281828];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->g=(BIGNUM*)&copydata[281828];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->pub_key=(BIGNUM*)&copydata[281828];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->priv_key=(BIGNUM*)&copydata[281828];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->method_mont_p=(BN_MONT_CTX*)&copydata[281828];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->q=(BIGNUM*)&copydata[281828];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->j=(BIGNUM*)&copydata[281828];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->seed=(unsigned char*)&copydata[281828];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->counter=(BIGNUM*)&copydata[281928];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->meth=(DH_METHOD*)&copydata[281928];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->meth->name=(char*)&copydata[288680];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->meth->app_data=(char*)&copydata[288780];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_dh_tmp->engine=(ENGINE*)&copydata[288880];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->sess_cert->peer_ecdh_tmp=(EC_KEY*)&copydata[288880];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->peer=(X509*)&copydata[295632];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->cipher=(SSL_CIPHER*)&copydata[295632];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->cipher->name=(char*)&copydata[302472];
			_n_do_ssl_write_s_copy->d1->w_msg_hdr.saved_retransmit_state.session->ciphers=(struct stack_st_SSL_CIPHER*)&copydata[302572];
			_n_do_ssl_write_s_copy->msg_callback_arg=(void*)&copydata[323228];
			_n_do_ssl_write_s_copy->param=(X509_VERIFY_PARAM*)&copydata[323328];
			_n_do_ssl_write_s_copy->param->name=(char*)&copydata[330284];
			_n_do_ssl_write_s_copy->param->policies=(struct stack_st_ASN1_OBJECT*)&copydata[330384];
			_n_do_ssl_write_s_copy->cipher_list=(struct stack_st_SSL_CIPHER*)&copydata[330384];
			_n_do_ssl_write_s_copy->cipher_list_by_id=(struct stack_st_SSL_CIPHER*)&copydata[330384];
			_n_do_ssl_write_s_copy->enc_read_ctx=(EVP_CIPHER_CTX*)&copydata[330384];
			_n_do_ssl_write_s_copy->read_hash=(EVP_MD_CTX*)&copydata[330384];
			_n_do_ssl_write_s_copy->expand=(COMP_CTX*)&copydata[330384];
			_n_do_ssl_write_s_copy->enc_write_ctx=(EVP_CIPHER_CTX*)&copydata[330384];
			_n_do_ssl_write_s_copy->write_hash=(EVP_MD_CTX*)&copydata[330384];
			_n_do_ssl_write_s_copy->compress=(COMP_CTX*)&copydata[330384];
			_n_do_ssl_write_s_copy->cert=(struct cert_st*)&copydata[330384];
			_n_do_ssl_write_s_copy->cert->key=(CERT_PKEY*)&copydata[337636];
			_n_do_ssl_write_s_copy->cert->rsa_tmp=(RSA*)&copydata[337636];
			_n_do_ssl_write_s_copy->cert->dh_tmp=(DH*)&copydata[337636];
			_n_do_ssl_write_s_copy->cert->ecdh_tmp=(EC_KEY*)&copydata[337636];
			_n_do_ssl_write_s_copy->session=(SSL_SESSION*)&copydata[337636];
			_n_do_ssl_write_s_copy->ctx=(SSL_CTX*)&copydata[337636];
			_n_do_ssl_write_s_copy->ctx->method=(SSL_METHOD*)&copydata[345624];
			_n_do_ssl_write_s_copy->ctx->cipher_list=(struct stack_st_SSL_CIPHER*)&copydata[345624];
			_n_do_ssl_write_s_copy->ctx->cipher_list_by_id=(struct stack_st_SSL_CIPHER*)&copydata[345624];
			_n_do_ssl_write_s_copy->ctx->cert_store=(struct x509_store_st*)&copydata[345624];
			_n_do_ssl_write_s_copy->ctx->cert_store->objs=(struct stack_st_X509_OBJECT*)&copydata[353756];
			_n_do_ssl_write_s_copy->ctx->cert_store->get_cert_methods=(struct stack_st_X509_LOOKUP*)&copydata[361920];
			_n_do_ssl_write_s_copy->ctx->cert_store->param=(X509_VERIFY_PARAM*)&copydata[370116];
			_n_do_ssl_write_s_copy->ctx->sessions=(struct lhash_st_SSL_SESSION*)&copydata[370116];
			_n_do_ssl_write_s_copy->ctx->session_cache_head=(struct ssl_session_st*)&copydata[378316];
			_n_do_ssl_write_s_copy->ctx->session_cache_tail=(struct ssl_session_st*)&copydata[378316];
			_n_do_ssl_write_s_copy->ctx->app_verify_arg=(void*)&copydata[378316];
			_n_do_ssl_write_s_copy->ctx->default_passwd_callback_userdata=(void*)&copydata[378416];
			_n_do_ssl_write_s_copy->ctx->rsa_md5=(EVP_MD*)&copydata[378516];
			_n_do_ssl_write_s_copy->ctx->md5=(EVP_MD*)&copydata[378516];
			_n_do_ssl_write_s_copy->ctx->sha1=(EVP_MD*)&copydata[378516];
			_n_do_ssl_write_s_copy->ctx->extra_certs=(struct stack_st_X509*)&copydata[378516];
			_n_do_ssl_write_s_copy->ctx->comp_methods=(struct stack_st_SSL_COMP*)&copydata[378516];
			_n_do_ssl_write_s_copy->ctx->client_CA=(struct stack_st_X509_NAME*)&copydata[386748];
			_n_do_ssl_write_s_copy->ctx->cert=(struct cert_st*)&copydata[395012];
			_n_do_ssl_write_s_copy->ctx->msg_callback_arg=(void*)&copydata[395012];
			_n_do_ssl_write_s_copy->ctx->param=(X509_VERIFY_PARAM*)&copydata[395112];
			_n_do_ssl_write_s_copy->ctx->client_cert_engine=(ENGINE*)&copydata[395112];
			_n_do_ssl_write_s_copy->ctx->tlsext_servername_arg=(void*)&copydata[395112];
			_n_do_ssl_write_s_copy->ctx->tlsext_status_arg=(void*)&copydata[395212];
			_n_do_ssl_write_s_copy->ctx->tlsext_opaque_prf_input_callback_arg=(void*)&copydata[395312];
			_n_do_ssl_write_s_copy->ctx->psk_identity_hint=(char*)&copydata[395412];
			_n_do_ssl_write_s_copy->ctx->wbuf_freelist=(struct ssl3_buf_freelist_st*)&copydata[395512];
			_n_do_ssl_write_s_copy->ctx->wbuf_freelist->head=(struct ssl3_buf_freelist_entry_st*)&copydata[403800];
			_n_do_ssl_write_s_copy->ctx->rbuf_freelist=(struct ssl3_buf_freelist_st*)&copydata[412096];
			_n_do_ssl_write_s_copy->ctx->srp_ctx.SRP_cb_arg=(void*)&copydata[420520];
			_n_do_ssl_write_s_copy->ctx->srp_ctx.login=(char*)&copydata[420620];
			_n_do_ssl_write_s_copy->ctx->srp_ctx.N=(BIGNUM*)&copydata[420720];
			_n_do_ssl_write_s_copy->ctx->srp_ctx.g=(BIGNUM*)&copydata[420720];
			_n_do_ssl_write_s_copy->ctx->srp_ctx.s=(BIGNUM*)&copydata[420720];
			_n_do_ssl_write_s_copy->ctx->srp_ctx.B=(BIGNUM*)&copydata[420720];
			_n_do_ssl_write_s_copy->ctx->srp_ctx.A=(BIGNUM*)&copydata[420720];
			_n_do_ssl_write_s_copy->ctx->srp_ctx.a=(BIGNUM*)&copydata[420720];
			_n_do_ssl_write_s_copy->ctx->srp_ctx.b=(BIGNUM*)&copydata[420720];
			_n_do_ssl_write_s_copy->ctx->srp_ctx.v=(BIGNUM*)&copydata[420720];
			_n_do_ssl_write_s_copy->ctx->srp_ctx.info=(char*)&copydata[420720];
			_n_do_ssl_write_s_copy->ctx->next_protos_advertised_cb_arg=(void*)&copydata[420820];
			_n_do_ssl_write_s_copy->ctx->next_proto_select_cb_arg=(void*)&copydata[420920];
			_n_do_ssl_write_s_copy->ctx->srtp_profiles=(struct stack_st_SRTP_PROTECTION_PROFILE*)&copydata[421020];
			_n_do_ssl_write_s_copy->client_CA=(struct stack_st_X509_NAME*)&copydata[429476];
			_n_do_ssl_write_s_copy->tlsext_debug_arg=(void*)&copydata[429476];
			_n_do_ssl_write_s_copy->tlsext_hostname=(char*)&copydata[429576];
			_n_do_ssl_write_s_copy->tlsext_ocsp_ids=(struct stack_st_OCSP_RESPID*)&copydata[429676];
			_n_do_ssl_write_s_copy->tlsext_ocsp_exts=(X509_EXTENSIONS*)&copydata[438132];
			_n_do_ssl_write_s_copy->tlsext_ocsp_resp=(unsigned char*)&copydata[438132];
			_n_do_ssl_write_s_copy->tlsext_ecpointformatlist=(unsigned char*)&copydata[438232];
			_n_do_ssl_write_s_copy->tlsext_ellipticcurvelist=(unsigned char*)&copydata[438332];
			_n_do_ssl_write_s_copy->tlsext_opaque_prf_input=(void*)&copydata[438432];
			_n_do_ssl_write_s_copy->tlsext_session_ticket=(TLS_SESSION_TICKET_EXT*)&copydata[438532];
			_n_do_ssl_write_s_copy->tlsext_session_ticket->data=(void*)&copydata[447004];
			_n_do_ssl_write_s_copy->tls_session_ticket_ext_cb_arg=(void*)&copydata[447104];
			_n_do_ssl_write_s_copy->tls_session_secret_cb_arg=(void*)&copydata[447204];
			_n_do_ssl_write_s_copy->initial_ctx=(SSL_CTX*)&copydata[447304];
			_n_do_ssl_write_s_copy->next_proto_negotiated=(unsigned char*)&copydata[447304];
			_n_do_ssl_write_s_copy->srtp_profiles=(struct stack_st_SRTP_PROTECTION_PROFILE*)&copydata[447404];
			_n_do_ssl_write_s_copy->srtp_profile=(SRTP_PROTECTION_PROFILE*)&copydata[447404];
			_n_do_ssl_write_s_copy->srtp_profile->name=(char*)&copydata[455892];
			_n_do_ssl_write_buf_copy=(unsigned char*)&copydata[455992];
			_n_do_ssl_write_len_copy=(unsigned int)copydata[456092];
			_n_do_ssl_write_p_copy=(unsigned int)copydata[456096];
			_n_do_ssl_write_mac_size_copy=(int)copydata[456100];
			_n_do_ssl_write_pp_copy=(unsigned char*)&copydata[456104];
			_n_do_ssl_write_olen_copy=(unsigned int)copydata[456204];
			n_do_ssl_write_return_copy=(int)copydata[456208];
			write_pending_return_copy=(int)copydata[456212];
			loop++;
		}
	}else
	{
		_n_do_ssl_write_s_ = _n_do_ssl_write_s_copy;
		_n_do_ssl_write_buf_ = _n_do_ssl_write_buf_copy;
		_n_do_ssl_write_len_ = _n_do_ssl_write_len_copy;
		_n_do_ssl_write_p_ = _n_do_ssl_write_p_copy;
		_n_do_ssl_write_mac_size_ = _n_do_ssl_write_mac_size_copy;
		_n_do_ssl_write_pp_ = _n_do_ssl_write_pp_copy;
		_n_do_ssl_write_olen_ = _n_do_ssl_write_olen_copy;
		n_do_ssl_write_return_ = n_do_ssl_write_return_copy;
		write_pending_return_ = write_pending_return_copy;
		_n_do_ssl_write_len_=(unsigned int)data[0];
		_n_do_ssl_write_s_->rbio->cb_arg=(char)&data[4];
		_n_do_ssl_write_s_->sid_ctx_length=(unsigned int)data[104];
		if (size>=108)
		{
			s2_pkt610s2_pkt490_1(_n_do_ssl_write_s_,_n_do_ssl_write_buf_,_n_do_ssl_write_len_,_n_do_ssl_write_p_,_n_do_ssl_write_mac_size_,_n_do_ssl_write_pp_,_n_do_ssl_write_olen_,n_do_ssl_write_return_,write_pending_return_);
		loop++;
		}
	}
	cout<<realloop<<"	realloop time.."<<endl
	cout<<size<<"	size of every time.."<<endl;
	real_loop++;
}
